CREATE TABLE IF NOT EXISTS telemetry_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL,
    source_asset VARCHAR(255) NOT NULL,
    user_principal VARCHAR(255) NOT NULL,
    bytes_transferred INTEGER NOT NULL,
    anomaly_score FLOAT NOT NULL,
    status VARCHAR(50) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_telemetry_source_timestamp 
ON telemetry_logs (source_asset, timestamp DESC);
